export const projectsData = [
  {
    id: 6,
    title: "Solventa Trade",
    description:
      "A real full-stack trade and consulting project that I actively manage, built with React, TypeScript, Node.js, MongoDB, and Tailwind CSS for international business workflows.",
    image: "https://www.solventatrade.eu/image.jpg",
    technologies: [
      "React",
      "TypeScript",
      "Node.js",
      "MongoDB",
      "Tailwind CSS",
      "Express",
      "Mongoose",
      "Vite",
    ],
    githubUrl: "https://github.com/jenyaproviz/solventa-trade.git",
    liveUrl: "https://www.solventatrade.eu/",
    category: "Full Stack",
  },
  {
    id: 5,
    title: "SmartMRP AI Assistant",
    description:
      "AI-based inventory planning assistant built as the final project of the AI Experts course, with demand forecasting, shortage-risk analysis, purchase recommendations, and order-risk review for manufacturing data.",
    image: "/project-images/SmartMRP_img.png",
    technologies: ["Python", "OpenAI API"],
    githubUrl: "https://github.com/jenyaproviz/smartMRP_AI",
    category: "Full Stack",
  },
  {
    id: 1,
    title: "Blog Platform",
    description:
      "A full-stack blog website built as a final project with React and Node.js. Features user authentication, post management, dark theme, and responsive design.",
    image: "/project-images/Blog_img.png",
    technologies: [
      "React",
      "TypeScript",
      "Node.js",
      "MongoDB",
      "Redux",
      "Tailwind CSS",
      "Express",
    ],
    githubUrl: "https://github.com/jenyaproviz/Final-Project-Blog-main.git",
    liveUrl: "https://final-project-blog-main.vercel.app/",
    category: "Full Stack",
  },
  {
    id: 2,
    title: "Raven Game",
    description:
      "Small JavaScript canvas game where you click flying ravens to score points.",
    image: "/project-images/Raven_game_img.png",
    technologies: ["JavaScript", "CSS3", "HTML5"],
    githubUrl: "https://github.com/jenyaproviz/Raven-game.git",
    liveUrl: "https://ravengame-three.vercel.app/",
    category: "Frontend",
  },
  {
    id: 3,
    title: "Musician Site",
    description:
      "Marketing website for a musician, built as a final project, with a responsive layout, custom sections, and lightweight frontend interactions.",
    image: "/project-images/Musician_site_img.png",
    technologies: ["HTML", "CSS", "JavaScript"],
    githubUrl: "https://github.com/jenyaproviz/Musician-Site.git",
    liveUrl: "https://jenyaproviz.github.io/Musician-Site/",
    category: "Frontend",
  },
  {
    id: 4,
    title: "JobPilot",
    description:
      "Full-stack job search application with a React frontend, TypeScript and Express API, and an MCP-based AI service for smarter search and analysis workflows.",
    image: "/project-images/JobPilot_img.png",
    technologies: [
      "React",
      "Node.js",
      "MongoDB",
      "TypeScript",
      "Tailwind CSS",
      "Vite",
      "Redux Toolkit",
      "Axios",
      "Express",
      "OpenAI API",
      "Mongoose",
      "Socket.io",
      "JWT",
      "Chart.js",
      "Redis",
    ],
    githubUrl: "https://github.com/jenyaproviz/JobPilot.git",
    liveUrl: "https://job-pilot-client.vercel.app/",
    category: "Full Stack",
  },
];