export const projectsData = [
  {
    id: 6,
    title: "Solventa Trade",
    description:
      "Website for an international sourcing and procurement company. I developed and deployed the site and handle its ongoing maintenance.",
    image: "https://www.solventatrade.eu/image.jpg",
    technologies: [
      "React",
      "TypeScript",
      "Node.js",
      "MongoDB",
      "Tailwind CSS",
      "Express",
      "Mongoose",
      "Vite",
      "Render",
    ],
    githubUrl: "https://github.com/jenyaproviz/solventa-trade.git",
    liveUrl: "https://www.solventatrade.eu/",
    category: "Full Stack",
  },
  {
    id: 5,
    title: "SmartMRP AI Assistant",
    description:
      "Inventory planning assistant developed for the AI Experts course. Uses manufacturing data for demand forecasting, shortage analysis, purchase recommendations, and order-risk review.",
    image: "/project-images/SmartMRP_img.png",
    technologies: ["Python", "OpenAI API"],
    githubUrl: "https://github.com/jenyaproviz/smartMRP_AI",
    category: "Full Stack",
  },
  {
    id: 1,
    title: "Blog Platform",
    description:
      "Course project built with React and Node.js. Includes user authentication, creating and editing posts, comments, and likes.",
    image: "/project-images/Blog_img.png",
    technologies: [
      "React",
      "TypeScript",
      "Node.js",
      "MongoDB",
      "Redux",
      "Tailwind CSS",
      "Express",
    ],
    githubUrl: "https://github.com/jenyaproviz/Final-Project-Blog-main.git",
    liveUrl: "https://final-project-blog-main.vercel.app/",
    category: "Full Stack",
  },
  {
    id: 2,
    title: "Raven Game",
    description:
      "Small JavaScript canvas game where you click flying ravens to score points.",
    image: "/project-images/Raven_game_img.png",
    technologies: ["JavaScript", "CSS3", "HTML5"],
    githubUrl: "https://github.com/jenyaproviz/Raven-game.git",
    liveUrl: "https://ravengame-three.vercel.app/",
    category: "Frontend",
  },
  {
    id: 3,
    title: "Musician Site",
    description:
      "Course project for a musician's website, built with HTML, CSS, and JavaScript.",
    image: "/project-images/Musician_site_img.png",
    technologies: ["HTML", "CSS", "JavaScript"],
    githubUrl: "https://github.com/jenyaproviz/Musician-Site.git",
    liveUrl: "https://jenyaproviz.github.io/Musician-Site/",
    category: "Frontend",
  },
  {
    id: 4,
    title: "Chaos Pilots",
    description:
      "Website for the Chaos Pilots alternative rock band, with music, upcoming events, and social links.",
    image: "/project-images/Chaos Pilots.png",
    technologies: [
      "React",
      "Node.js",
      "JavaScript",
      "Tailwind CSS",
      "Vercel",
      "Render",
    ],
    githubUrl: "",
    liveUrl: "https://chaospilots-band-website.vercel.app/",
    category: "Full Stack",
  },
  {
    id: 7,
    hidden: true,
    title: "JobPilot",
    description:
      "Job search application with a React frontend, a TypeScript and Express API, and an MCP-based AI service for search and analysis.",
    image: "/project-images/JobPilot_img.png",
    technologies: [
      "React",
      "Node.js",
      "MongoDB",
      "TypeScript",
      "Tailwind CSS",
      "Vite",
      "Redux Toolkit",
      "Axios",
      "Express",
      "OpenAI API",
      "Mongoose",
      "Socket.io",
      "JWT",
      "Chart.js",
      "Redis",
    ],
    githubUrl: "https://github.com/jenyaproviz/JobPilot.git",
    liveUrl: "https://job-pilot-client.vercel.app/",
    category: "Full Stack",
  },
];